// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://netwujzhcftuwzbvmpfi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ldHd1anpoY2Z0dXd6YnZtcGZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NTI1NTYsImV4cCI6MjA2NDEyODU1Nn0.qXZ2cZMvI3JOBrKtQHIwyxHWiwfNdkTYoXcRWOCcyKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);